FROM golang:1.23.1 AS builder
ENV CGO_ENABLED=0
ARG BUILD_REF

COPY . /ultimate-service

WORKDIR /ultimate-service

RUN go build -ldflags "-X main.build=${BUILD_REF}"

FROM alpine:3.14
ARG BUILD_DATE
ARG BUILD_REF
COPY --from=builder /ultimate-service /ultimate-service/ultimate-service
WORKDIR /ultimate-service
CMD ["./ultimate-service"]

