FROM golang:1.23.1 AS builder
ENV CGO_ENABLED=0
ARG BUILD_REF

COPY . /service

WORKDIR /service/app/services/sales-api

RUN go build -ldflags "-X main.build=${BUILD_REF}"

FROM alpine:3.14
ARG BUILD_DATE
ARG BUILD_REF
COPY --from=builder /service/app/services/sales-api/sales-api /service/sales-api
WORKDIR /service
CMD ["./sales-api"]

